### ISSUE TITLE
Does ClientToServerChannelHandler have concurrency problem

### ISSUE THREAD

**Issue by ielts0909** [rchodava/datamill#69]
class ClientToServerChannelHandler is not a ThreadSafe class, but the member variable `serverRequest` and `bodyStream`  are shared in channel read. i'm not sure channelRead is thread safe, cause i haven't see descibtion in methad.

**Comment by rchodava** [comment]
Hi @ielts0909 , are you seeing an issue around the thread safety here? As far as I know, the code that runs as part of a single ChannelPipeline, including Handlers is thread safe (documented in ChannelPipeline) in Netty.

**Comment by ielts0909** [comment]
ok i see the document thank you !
